/**
 * Résout une icône lucide-react par son nom (chaîne).
 * Permet à site-content.ts / bys-content.ts de référencer les icônes par
 * string ("Globe", "Phone"...) sans imposer d'imports React au fichier de config.
 *
 * Liste complète : https://lucide.dev/icons/
 */

import {
  Banknote,
  BarChart3,
  BrainCircuit,
  Briefcase,
  Building2,
  Calculator,
  ClipboardCheck,
  Clock,
  Code,
  Compass,
  Cpu,
  Eye,
  FileText,
  Globe,
  Inbox,
  Hammer,
  Handshake,
  HardHat,
  Heart,
  HeartHandshake,
  HelpCircle,
  Home,
  Lightbulb,
  LineChart,
  Mail,
  MapPin,
  Megaphone,
  MessagesSquare,
  MonitorSmartphone,
  PackageCheck,
  Palette,
  Paintbrush,
  Phone,
  Radar,
  Scale,
  Search,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Sprout,
  Star,
  Target,
  Telescope,
  TrendingUp,
  Truck,
  Users,
  UserSearch,
  Utensils,
  Waypoints,
  Wine,
  Wrench,
  type LucideIcon,
} from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  Banknote,
  BarChart3,
  BrainCircuit,
  Briefcase,
  Building2,
  Calculator,
  ClipboardCheck,
  Clock,
  Code,
  Compass,
  Cpu,
  Eye,
  FileText,
  Globe,
  Inbox,
  Hammer,
  Handshake,
  HardHat,
  Heart,
  HeartHandshake,
  Home,
  Lightbulb,
  LineChart,
  Mail,
  MapPin,
  Megaphone,
  MessagesSquare,
  MonitorSmartphone,
  PackageCheck,
  Palette,
  Paintbrush,
  Phone,
  Radar,
  Scale,
  Search,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Sprout,
  Star,
  Target,
  Telescope,
  TrendingUp,
  Truck,
  Users,
  UserSearch,
  Utensils,
  Waypoints,
  Wine,
  Wrench,
}

export function getIcon(name?: string): LucideIcon {
  if (!name) return HelpCircle
  return iconMap[name] ?? HelpCircle
}

export type IconName = keyof typeof iconMap
